db: &DB
  image: postgres:9.4.5
  ports:
    - 5432
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password

local:
  build: .
  command: sh -c "mix phoenix.server"
  ports:
    - "4000:4000"
  environment: &ENV
    VIRTUAL_HOST: blah
    VIRTUAL_PORT: 4000
    DATABASE_URL: ecto://user:password@db/rest_api_dev
  links:
    - db:db
